### PR TITLE
Security fixes: Created secure session management, password hashing w…

### PR DESCRIPTION
**Pull request by bellizzij**
…ith salt and removed SQL injection vulnerability

### CODE REVIEW

**Comment by mikaelstaer** [comment]
Amazing. I was going to sit down today and figure this out - thanks so much.

**Comment by bellizzij** [comment]
Please note, some fixes with regards to password hashing will require PHP version > 5

**Comment by mikaelstaer** [comment]
Just realized - AJAX calls require a fix too. Projects module/update.php
for example. I'm looking into this now.

--
Mikael Staer Nathan
www.mikaelstaer.com
www.staernathan.com
647 240 8685

**Comment by mikaelstaer** [comment]
Fixed - session_start() needed to be added to launch.php in AJAX section.

--
Mikael Staer Nathan
www.mikaelstaer.com
www.staernathan.com
647 240 8685

**Comment by bellizzij** [comment]
Yes I forgot to merge that!

**Pull request merged**
